name: flutter_common_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #디자인
  cupertino_icons: ^1.0.2
  group_button: ^3.0.1
  menu_button: ^1.4.2+1
  #custom_pop_up_menu : ^1.2.0
  flutter_rating_bar: ^4.0.0
  introduction_screen: ^2.1.0
  flutter_calendar_carousel: ^2.0.1
  expandable_page_view: ^1.0.6 #PageView 대체

  #equatable(서로다른 인스턴스 같은 인스턴스인지 판단용)
  equatable: ^2.0.3

  #상태관리
  get: ^4.3.0

  #로컬저장소
  hive: ^2.0.4

  #파일시스템 경로접근용
  path_provider: ^2.0.2

  #정보(패키지,기기)
  package_info: ^2.0.2
  device_info: ^2.0.2

  #이미지 & 파일
  photo_view: ^0.12.0
  # image_picker: ^0.7.4 #0.7.5부터는 permission을 무시하고 접근이 가능해서 버전고정함.
  images_picker: ^1.2.4
  cached_network_image: ^3.1.0
  transparent_image: ^2.0.0
  file_picker: ^3.0.3
  flutter_svg: ^0.22.0 

  ##알림

  #토스트 메시지
  fluttertoast: ^8.0.7
  #다이얼로그
  adaptive_dialog: ^1.1.0
  #알림 메시지
  flutter_local_notifications: ^7.0.0
  #바텀 시트
  modal_bottom_sheet: ^2.0.0

  #통신
  http: ^0.13.3
  html: ^0.15.0
  # dio: ^4.0.0
  graphql_flutter: ^5.0.0

  #전역 세팅
  global_configuration: ^2.0.0-nullsafety.1

  #로딩 이펙트
  shimmer: ^2.0.0

  #다국어 지원 & date/number format & 양방향텍스트
  intl: ^0.17.0

  #url연결(http, 문자, 전화..)
  url_launcher: ^6.0.9

  #파이어베이스 & 파이어스토어
  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.4.0
  firebase_storage: ^10.0.1

  #소셜로그인
  google_sign_in: ^5.0.5

  #로그
  logger: ^1.0.0

  #권한 관리
  permission_handler: ^8.1.4

  #공유기능
  share: ^2.0.4

  #링크위젯
  flutter_linkify: ^5.0.2

  #백그라운드 실행
  workmanager: ^0.4.1 

  #최초 빌드 후 코드실행하게 해주는 패키지
  after_layout: ^1.1.0
  
  #인덱스에 맞게 스크롤
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  
  #포맷 패턴
  pattern_formatter: ^2.0.0
  #파일 사이즈 변환
  filesize: ^2.0.1

  #비디오
  #video_player: ^2.0.2
  #chewie: ^1.0.0

  #구글 폰트
  #google_fonts: ^2.0.0

  #동적 화면
  #flutter_screenutil: ^5.0.0+2

  #광고
  #google_mobile_ads: ^0.13.2

  #결재
  iamport_flutter:
    path: ext_package/iamport_flutter

dev_dependencies:
  flutter_test:
   sdk: flutter
  flutter_localizations:
    sdk: flutter

  #앱 아이콘 수정(flutter pub run flutter_launcher_icons:main)
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/error/
    - assets/logos/
    - assets/gifs/
    - assets/icons/
    - assets/cfg/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans/NotoSansKR-Thin.otf
        - asset: assets/fonts/NotoSans/NotoSansKR-Light.otf
          weight: 300
        - asset: assets/fonts/NotoSans/NotoSansKR-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSans/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSans/NotoSansKR-Bold.otf
          weight: 700
        - asset: assets/fonts/NotoSans/NotoSansKR-Black.otf
          weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
